/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.twitter.streaming;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class tweets_ser extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"tweets_ser\",\"namespace\":\"com.eduonix.hadoop.partone\",\"fields\":[{\"name\":\"text\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence text;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public tweets_ser() {}

  /**
   * All-args constructor.
   */
  public tweets_ser(java.lang.CharSequence text) {
    this.text = text;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return text;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: text = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'text' field.
   */
  public java.lang.CharSequence getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.lang.CharSequence value) {
    this.text = value;
  }

  /** Creates a new tweets_ser RecordBuilder */
  public static tweets_ser.Builder newBuilder() {
    return new tweets_ser.Builder();
  }
  
  /** Creates a new tweets_ser RecordBuilder by copying an existing Builder */
  public static tweets_ser.Builder newBuilder(tweets_ser.Builder other) {
    return new tweets_ser.Builder(other);
  }
  
  /** Creates a new tweets_ser RecordBuilder by copying an existing tweets_ser instance */
  public static tweets_ser.Builder newBuilder(tweets_ser other) {
    return new tweets_ser.Builder(other);
  }
  
  /**
   * RecordBuilder for tweets_ser instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<tweets_ser>
    implements org.apache.avro.data.RecordBuilder<tweets_ser> {

    private java.lang.CharSequence text;

    /** Creates a new Builder */
    private Builder() {
      super(tweets_ser.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(tweets_ser.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.text)) {
        this.text = data().deepCopy(fields()[0].schema(), other.text);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing tweets_ser instance */
    private Builder(tweets_ser other) {
            super(tweets_ser.SCHEMA$);
      if (isValidValue(fields()[0], other.text)) {
        this.text = data().deepCopy(fields()[0].schema(), other.text);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'text' field */
    public java.lang.CharSequence getText() {
      return text;
    }
    
    /** Sets the value of the 'text' field */
    public tweets_ser.Builder setText(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.text = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'text' field has been set */
    public boolean hasText() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'text' field */
    public tweets_ser.Builder clearText() {
      text = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public tweets_ser build() {
      try {
        tweets_ser record = new tweets_ser();
        record.text = fieldSetFlags()[0] ? this.text : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
